# action名称
name: Push Release

# 当代码合并到master分支的时候，执行下列脚本
on:
  push:
    branches: [ main ]

# 任务
jobs:
# publish-npm任务
  publish-npm:
  # 在ubuntu最新版本的虚拟机执行
    runs-on: ubuntu-latest
    # 设置变量
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      # 检查并切换到master分支
      - name: 检查master分支
      # 使用actions/checkout插件
        uses: actions/checkout@main

      # 安装node
      - name: 设置Node.js
      # 使用actions/setup-node插件
        uses: actions/setup-node@main
        with:
        # node版本
          node-version: ${{ matrix.node-version }}

# 初始化缓存
      - name:  缓存
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

# 读取当前版本号
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
        # 读取根路径下的package.json
          path: ./package.json
          property: version

# 发布NPM包
      - name: 发布NPM包
      # 执行发布代码
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access=public
        env:
        # 配置 npm access token 环境变量
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

